"""
routers/greeting.py
===================
Greeting endpoint — returns a personalised, AI-generated workspace greeting.

The greeting is generated by Gemini based on:
- The user's first name (from auth context)
- The client's local hour (sent as a query param)
- The user's project count (sent as a query param)

Falls back to a deterministic static greeting if the GEMINI_API_KEY is
unset or the AI call fails, so the frontend is never blocked.

Endpoint
--------
GET /api/v1/greeting?local_hour=9&project_count=3
"""

from __future__ import annotations

import json
import logging
from typing import Optional

from fastapi import APIRouter, Depends, Query
from pydantic import BaseModel

from auth.dependencies import optional_current_user
from config import settings

logger = logging.getLogger(__name__)
router = APIRouter()


# ── Fallback (no API key / AI failure) ───────────────────────────────────────

def _time_period(hour: int) -> str:
    if 5 <= hour < 12:
        return "morning"
    if 12 <= hour < 17:
        return "afternoon"
    if 17 <= hour < 21:
        return "evening"
    return "night"


def _static_greeting(full_name: Optional[str], hour: int, has_projects: bool) -> dict[str, str]:
    period = _time_period(hour)
    first = full_name.split()[0] if full_name else None
    suffix = f", {first}" if first else ""

    headings = {
        "morning":   f"Good morning{suffix}.",
        "afternoon": f"Good afternoon{suffix}.",
        "evening":   f"Good evening{suffix}.",
        "night":     f"Still at it{suffix}?" if first else "Working late?",
    }
    subs = {
        ("morning",   True):  "Here's what's on your board.",
        ("morning",   False): "Ready to start your first project?",
        ("afternoon", True):  "Pick up where you left off.",
        ("afternoon", False): "Start something new today.",
        ("evening",   True):  "Let's make some progress.",
        ("evening",   False): "A good time to start something new.",
        ("night",     True):  "Your projects are ready.",
        ("night",     False): "Start a new project below.",
    }
    return {
        "heading": headings[period],
        "sub": subs[(period, has_projects)],
    }


# ── Lazy LLM init ─────────────────────────────────────────────────────────────

_llm = None

def _get_llm():
    global _llm
    if _llm is None and settings.GEMINI_API_KEY:
        from langchain_google_genai import ChatGoogleGenerativeAI
        _llm = ChatGoogleGenerativeAI(
            model=settings.ACTION_MODEL,
            google_api_key=settings.GEMINI_API_KEY,
            temperature=1.0,
            max_tokens=150,
        )
    return _llm


# ── Schema ────────────────────────────────────────────────────────────────────

class GreetingResponse(BaseModel):
    heading: str
    sub: str


# ── Endpoint ──────────────────────────────────────────────────────────────────

@router.get("", response_model=GreetingResponse)
async def get_greeting(
    local_hour: int = Query(ge=0, le=23, description="Client's local hour (0–23)."),
    project_count: int = Query(ge=0, default=0, description="Number of the user's projects."),
    user_name: Optional[str] = Query(None, description="User's display name (fallback if unauthenticated)."),
    user=Depends(optional_current_user),
) -> GreetingResponse:
    full_name = (user.full_name if user else None) or user_name
    has_projects = project_count > 0
    llm = _get_llm()

    if llm is None:
        data = _static_greeting(full_name, local_hour, has_projects)
        return GreetingResponse(**data)

    period = _time_period(local_hour)
    first_name = full_name.split()[0] if full_name else None

    name_ctx = (
        f"The engineer's first name is {first_name}."
        if first_name
        else "The engineer's name is not known."
    )

    logger.info(name_ctx)
    project_ctx = (
        f"They currently have {project_count} project{'s' if project_count != 1 else ''} on the platform."
        if has_projects
        else "They have no projects yet, this may be their first time."
    )

    prompt = f"""You are the assistant embedded in StructAI Copilot, an AI-powered structural engineering workspace used by professional engineers.

Write a personalised workspace greeting to show at the top of the homepage.

Context:
- Time of day: {period} (local hour: {local_hour}:00)
- {name_ctx}
- {project_ctx}

Rules:
- "heading": warm, time-appropriate greeting. Max 7 words. Include first name if known.
- "sub": one helpful, contextual subtitle. Max 12 words. Reference their projects if they have any.
- Tone: calm, professional, encouraging. Not overly casual or corporate.
- Do NOT use exclamation marks.
- Return ONLY a valid JSON object — no markdown, no explanation.

Examples:
{{"heading": "Good morning, Adeyemi.", "sub": "Here's what's on your board today."}}
{{"heading": "Good afternoon.", "sub": "You have 3 active projects."}}
{{"heading": "Still at it, Sarah?", "sub": "Your Harbour Tower project is in progress."}}
{{"heading": "Good evening, James.", "sub": "Ready to make some progress tonight."}}
{{"heading": "Good morning.", "sub": "Create your first project to get started."}}"""

    try:
        from langchain_core.messages import HumanMessage

        response = await llm.ainvoke([HumanMessage(content=prompt)])
        content = response.text.strip()
        logger.info(content)
        # Strip markdown code fences if the model adds them
        if content.startswith("```"):
            content = "\n".join(content.split("\n")[1:])
            if content.endswith("```"):
                content = content[: content.rfind("```")]

        data = json.loads(content)
        heading = str(data.get("heading", "")).strip()
        sub = str(data.get("sub", "")).strip()

        if not heading or not sub:
            raise ValueError("AI returned empty greeting fields.")

        return GreetingResponse(heading=heading, sub=sub)

    except Exception as exc:
        logger.warning("Greeting AI call failed (%s) — using static fallback.", exc)
        data = _static_greeting(full_name, local_hour, has_projects)
        return GreetingResponse(**data)
