"use client";

import * as React from "react";
import { X } from "lucide-react";
import { useCanvasStore } from "@/stores/canvasStore";
import { useAnalysisStore } from "@/stores/analysisStore";
import type { MemberCheckStatus } from "@/types/analysis";

function asNum(v: unknown): number | undefined {
  return typeof v === "number" && Number.isFinite(v) ? v : undefined;
}

const STATUS_CLASS: Record<MemberCheckStatus, string> = {
  pass: "text-status-done",
  fail: "text-destructive",
  critical: "text-destructive",
  skipped: "text-muted-foreground",
};

/**
 * Foundation schedule — a compact table of the project's footings.
 *
 * Footings are auto-generated by the load takedown (one per base column) and now
 * persisted into the canvas geometry, so they appear here with their
 * analysis-derived size and bearing pressure. Type is shown (with the heuristic
 * recommendation when present); per-footing override + re-analysis is a follow-up.
 */
export function FoundationSchedule({ onClose }: { onClose: () => void }): React.ReactElement | null {
  const members = useCanvasStore((s) => s.members);
  const analysisMap = useAnalysisStore((s) => s.memberAnalysisMap);
  const getStatus = useAnalysisStore((s) => s.getMemberStatus);

  const footings = members.filter((m) => m.member_type === "footing");

  const rows = footings.map((f) => {
    const a = analysisMap.get(f.member_id);
    const cs = (a?.critical_sections ?? {}) as Record<string, unknown>;
    const geom = (cs.geometry ?? {}) as Record<string, unknown>;
    const pressures = (cs.pressures ?? {}) as Record<string, unknown>;
    const sources = f.meta._source_columns as string[] | undefined;
    return {
      id: f.member_id,
      column: sources?.join(" + ") ?? (f.meta._source_column as string | undefined) ?? "—",
      type: String(f.meta.footing_type ?? "pad"),
      recommended: f.meta.footing_type_recommended as string | undefined,
      B: asNum(geom.B_m),
      L: asNum(geom.L_m),
      q: asNum(pressures.q_uls_max),
      status: getStatus(f.member_id) as MemberCheckStatus,
    };
  });

  return (
    <div className="absolute top-16 right-4 z-30 w-[26rem] max-h-[70vh] overflow-y-auto bg-card/95 border border-border shadow-xl rounded-xl backdrop-blur-md animate-fade-in-up">
      <div className="flex items-center justify-between px-4 py-2.5 border-b border-border sticky top-0 bg-card/95">
        <span className="text-sm font-semibold text-foreground">
          Foundation Schedule
          <span className="ml-2 text-xs text-muted-foreground">({footings.length})</span>
        </span>
        <button onClick={onClose} className="text-muted-foreground hover:text-foreground" aria-label="Close">
          <X className="h-4 w-4" />
        </button>
      </div>

      {footings.length === 0 ? (
        <p className="px-4 py-6 text-xs text-muted-foreground text-center">
          No footings yet. Foundations are generated under columns during analysis.
        </p>
      ) : (
        <table className="w-full text-xs">
          <thead>
            <tr className="text-[10px] uppercase tracking-wider text-muted-foreground border-b border-border/60">
              <th className="text-left font-medium px-3 py-1.5">Footing</th>
              <th className="text-left font-medium px-2 py-1.5">Type</th>
              <th className="text-right font-medium px-2 py-1.5">B×L (m)</th>
              <th className="text-right font-medium px-2 py-1.5">q (kPa)</th>
              <th className="text-right font-medium px-3 py-1.5">Status</th>
            </tr>
          </thead>
          <tbody className="font-mono">
            {rows.map((r) => (
              <tr key={r.id} className="border-b border-border/30 last:border-0">
                <td className="px-3 py-1.5">
                  <span className="text-foreground">{r.id}</span>
                  <span className="block text-[10px] text-muted-foreground">on {r.column}</span>
                </td>
                <td className="px-2 py-1.5">
                  <span className="text-foreground capitalize">{r.type}</span>
                  {r.recommended && r.recommended !== r.type && (
                    <span className="block text-[10px] text-amber-500" title="Heuristic recommendation">
                      → {r.recommended}?
                    </span>
                  )}
                </td>
                <td className="px-2 py-1.5 text-right text-foreground">
                  {r.B && r.L ? `${r.B.toFixed(2)}×${r.L.toFixed(2)}` : "—"}
                </td>
                <td className="px-2 py-1.5 text-right text-foreground">
                  {r.q !== undefined ? r.q.toFixed(0) : "—"}
                </td>
                <td className={`px-3 py-1.5 text-right capitalize ${STATUS_CLASS[r.status]}`}>
                  {r.status}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}
