"""Added foreign key delete

Revision ID: 66ee758b4a8a
Revises: 7a30e00bb3cf
Create Date: 2026-05-27 20:24:27.129789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66ee758b4a8a'
down_revision: Union[str, Sequence[str], None] = '7a30e00bb3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('project_analysis_project_id_fkey'), 'project_analysis', type_='foreignkey')
    op.create_foreign_key(None, 'project_analysis', 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_design_project_id_fkey'), 'project_design', type_='foreignkey')
    op.create_foreign_key(None, 'project_design', 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_drawings_project_id_fkey'), 'project_drawings', type_='foreignkey')
    op.create_foreign_key(None, 'project_drawings', 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_geometry_project_id_fkey'), 'project_geometry', type_='foreignkey')
    op.create_foreign_key(None, 'project_geometry', 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_loads_project_id_fkey'), 'project_loads', type_='foreignkey')
    op.create_foreign_key(None, 'project_loads', 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_members_project_id_fkey'), 'project_members', type_='foreignkey')
    op.create_foreign_key(None, 'project_members', 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.create_foreign_key(op.f('project_members_project_id_fkey'), 'project_members', 'projects', ['project_id'], ['project_id'])
    op.drop_constraint(None, 'project_loads', type_='foreignkey')
    op.create_foreign_key(op.f('project_loads_project_id_fkey'), 'project_loads', 'projects', ['project_id'], ['project_id'])
    op.drop_constraint(None, 'project_geometry', type_='foreignkey')
    op.create_foreign_key(op.f('project_geometry_project_id_fkey'), 'project_geometry', 'projects', ['project_id'], ['project_id'])
    op.drop_constraint(None, 'project_drawings', type_='foreignkey')
    op.create_foreign_key(op.f('project_drawings_project_id_fkey'), 'project_drawings', 'projects', ['project_id'], ['project_id'])
    op.drop_constraint(None, 'project_design', type_='foreignkey')
    op.create_foreign_key(op.f('project_design_project_id_fkey'), 'project_design', 'projects', ['project_id'], ['project_id'])
    op.drop_constraint(None, 'project_analysis', type_='foreignkey')
    op.create_foreign_key(op.f('project_analysis_project_id_fkey'), 'project_analysis', 'projects', ['project_id'], ['project_id'])
    # ### end Alembic commands ###
